#### Libraries In Python

- Python libraries are collection of functions/methods that allows us to perform many actions without writing much/any code.
- For Machine Learning, there are primarily 4-5 important libraries which very importan to know:
1. Numpy
2. Pandas
3. Matplotlib
4. sklearn

#### Numpy - stands for numerical python

- It is the core library used for numerical and scientific computation work in python
- It consists of multidimensional array objects and a collection of routines for processing those arrays
- You can create a multi-dimensional array in python and there are certain methods available to play or manipulate these objects 

#### Creating Numpy Array
1. Single Dimensional 
2. Multi Dimensional 

In [1]:
# import numpy library for working with n-dimensional numpy array
import numpy as np

In [2]:
# Single dimension
n1 = np.array([2,4,6,8,10])

In [3]:
n1

array([ 2,  4,  6,  8, 10])

In [4]:
type(n1)

numpy.ndarray

In [6]:
# Multi Dimensional
n2 = np.array([[2,3,4,6],[4,6,8,12]])
n2

array([[ 2,  3,  4,  6],
       [ 4,  6,  8, 12]])

In [7]:
type(n2) # numpy.ndarray(n-dimensional array)

numpy.ndarray

In [8]:
# Initialize numpy array with only zeros - using zeros method

n3 = np.zeros((1,2)) # 1 rows , 2 columns 
n3

array([[0., 0.]])

In [11]:
n4 = np.zeros((3,4)) #3 rows, 4 columns 
n4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Initializing numpy array with same number - using full method -- syntax np.full(ndim, value to be filled in matrix)

n5 = np.full([3,3],20)
n5

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [15]:
n6 = np.full((4,5),5)
n6

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
# Initializing the numpy array of particular range - using arange method - syntax np.arange(start- incl, end-incl, step - excl)

n7 = np.arange(1,10)
n7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
n8 = np.arange(5,50,5) # start - 5 , end - 50, step difference - 5
n8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
# support if i want the 50 incl from the above 

n9 = np.arange(0,101, 10)
n9

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
# Initialize numpy array with random number -using random method -
# syntax np.random.submethod(low limit, upper limit, no of values)

n10 = np.random.random_integers(1,100,9)
n10

<ipython-input-34-387d448945fa>:4: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  n10 = np.random.random_integers(1,100,9)


array([55, 35, 92, 49,  2, 78, 36, 22, 81])

In [35]:
# Check or Change the shape of a numpy array

n11 = np.array([[2,6],[4,12]])
n11

array([[ 2,  6],
       [ 4, 12]])

In [36]:
n11.shape # shape function will show the share of the n dim array

(2, 2)

In [37]:
# change the shape of the array in numpy

n12 = np.array([[2,3,4],[4,6,8]])
n12

array([[2, 3, 4],
       [4, 6, 8]])

In [38]:
n12.shape = (3,2) # this will change the shape of the matrix
n12

array([[2, 3],
       [4, 4],
       [6, 8]])

#### Joining Numpy Arrays - Stacking numpy arrays

- There are mainly 3 methods through which we can stack/join array in numpy 
1. vstack - vertical stacking
2. hstack - horizontal stacking
3. column_stacking -  as per the name

In [40]:
n13 = np.array([1,2,3])
n13

array([1, 2, 3])

In [41]:
n14 = np.array([4,5,6])
n14

array([4, 5, 6])

In [43]:
# vstack method in numpy 

n15 = np.vstack((n13,n14))
n15

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# hstack mathod in numpy 

n16 = np.hstack((n13,n14))
n16

array([1, 2, 3, 4, 5, 6])

In [46]:
n17 = np.column_stack((n13,n14)) # first column the rows into column and there map both the arrays
n17 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
# Working with more vstack, hstack and column_stack method

n18 = np.arange(0,21,5)
n19 = np.arange(20,41,5)

In [57]:
n20 = np.vstack((n18,n19))
n20

array([[ 0,  5, 10, 15, 20],
       [20, 25, 30, 35, 40]])

In [58]:
n21 = n20 *2 
n21

array([[ 0, 10, 20, 30, 40],
       [40, 50, 60, 70, 80]])

In [59]:
# hstack 

n22 = np.hstack((n20,n21))
n22

array([[ 0,  5, 10, 15, 20,  0, 10, 20, 30, 40],
       [20, 25, 30, 35, 40, 40, 50, 60, 70, 80]])

In [60]:
# again vstack
n23 = np.vstack((n20,n21))
n23

array([[ 0,  5, 10, 15, 20],
       [20, 25, 30, 35, 40],
       [ 0, 10, 20, 30, 40],
       [40, 50, 60, 70, 80]])

In [61]:
# column_stacking - in case of more than 1 dimension column stack works similar to hstack

n24 = np.column_stack((n20,n21))
n24

array([[ 0,  5, 10, 15, 20,  0, 10, 20, 30, 40],
       [20, 25, 30, 35, 40, 40, 50, 60, 70, 80]])

In [65]:
# Intersection and Difference in Numpy array

n25 = np.arange(0,50,5)
n25

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [66]:
n26 = np.arange(25,75, 5)
n26

array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [67]:
# Intersection method - To check common element between the two array 

n27 = np.intersect1d(n25,n26)
n27

array([25, 30, 35, 40, 45])

In [68]:
# Difference method - find the element present in 1 of the array but not in other 

n28 = np.setdiff1d(n25,n26)
n28

array([ 0,  5, 10, 15, 20])

In [69]:
n29 = np.setdiff1d(n26,n25)
n29

array([50, 55, 60, 65, 70])

In [104]:
# Numpy Array Mathematics - Addition to numpy arrays 

n30 = np.array([21,41])
n31 = np.array([31,51])

In [105]:
n30

array([21, 41])

In [106]:
n31

array([31, 51])

In [107]:
# this will sum up all the values from both the arrays 
np.sum([n30,n31]) # pass arrays as list

144

In [108]:
# this will sum up all the value in arrays by columns - axis = 0 

np.sum([n30,n31], axis=0)

array([52, 92])

In [109]:
# this will add values of within array and show is on he given r*c combination

np.sum([n30,n31], axis=1)

array([62, 82])

In [119]:
# Basic Numpy Array Mathematics

n32 = np.arange(0,20,2)
n32

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [121]:
# Addition - Adding 5 in every element 

n32 + 5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [122]:
# Substract - Substracting 2 from every element 

n32 - 2

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [123]:
# Division - Dividing by 2 in every element 

n32/2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [124]:
# Multiplication - multiplying every element by 3

n32 * 3

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [128]:
# Some Methematical Function - Statstics 

n33 = np.arange(20,100,10)
n33

array([20, 30, 40, 50, 60, 70, 80, 90])

In [132]:
np.mean(n33) # mean

55.0

In [131]:
np.median(n33) #median

55.0

In [133]:
np.std(n33) #standard deviation

22.9128784747792

In [137]:
np.var(n33) # variance

525.0

In [138]:
np.sqrt(np.var(n33)) #standard deviation from variance

22.9128784747792

In [134]:
np.min(n33) # minimum value

20

In [135]:
np.max(n33) #maximum value

90

##### Saving and Loading Numpy Array

In [142]:
n34 = np.full((5,6),5)

In [143]:
n34

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [144]:
# saving numpy array 

# syntax -->  np.save(numpy name, numpy object)

np.save('my_numpy_example', n34)

In [146]:
# loading numpy array 

# syntax --> np.load(numpy name) - numpy object is stored in .npy extension

n35 = np.load('my_numpy_example.npy')

In [147]:
n35

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

#### Introduction to Pandas

- Pandas stands for Panel Data and it is the core library for data manipulation and analysis
- It can have single or multi-dimensional data for data manipulation 

- Data in Pandas:
1. Single Dimensional Data - Series Object 
2. Multi Dimensional Data - Data Frame

In [148]:
# Import Pandas 

import pandas as pd

In [151]:
# Create Pandas Series Object:

ps1 = pd.Series([1,2,3,4,5])
ps1

# below we can see series data with index details on the left side which starts from 0 

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [152]:
type(ps1)

pandas.core.series.Series

In [153]:
ps2 = pd.Series([10,20,30,50])
ps2

0    10
1    20
2    30
3    50
dtype: int64

In [159]:
# change the index of the series elements 

ps3  = pd.Series(np.arange(0,11,2))
ps3

0     0
1     2
2     4
3     6
4     8
5    10
dtype: int32

In [157]:
ps4  = pd.Series(np.arange(0,11,2), index=['a','b','c','d','e','f'])
ps4

# we can see that the index value for elements have been updated with new index value(string type)

a     0
b     2
c     4
d     6
e     8
f    10
dtype: int32

In [161]:
ps5 = pd.Series([50,55,65,72], index=['maths','science','physics','chemistry'])
ps5

# below we can see that the subject names are assigned as index value for the given marks 

maths        50
science      55
physics      65
chemistry    72
dtype: int64

In [163]:
# Creating a series object from a dictionary 

ps6 = pd.Series({'a':'apple', 'b':'orange', 'c':'banana', 'd':'grapes'})
ps6

#In dictionary, we create index/keys by default when creating series itself

a     apple
b    orange
c    banana
d    grapes
dtype: object

In [165]:
# We can change the index values in a dictionary

ps7 = pd.Series({'a':'apple', 'b':'orange', 'c':'banana', 'd':'grapes'}, index=['e','b','a','c'])
ps7

# you can see the updated index 

e       NaN
b    orange
a     apple
c    banana
dtype: object

In [167]:
# Extracting elements through the index value 

ps8 = pd.Series(np.arange(2,21,2))
ps8

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
dtype: int32

In [168]:
#extract the element of index no 4
ps8[4]

10

In [169]:
#extract the elements from index position starts from 4 to 7 from the series. index 4 is inclsive and position 8 is exclusive 
ps8[4:8]

4    10
5    12
6    14
7    16
dtype: int32

In [173]:
#Extract element from start till 4th position as 5th is exclusive
ps8[:5]

0     2
1     4
2     6
3     8
4    10
dtype: int32

In [175]:
# similary extract all the element start from index position 6 till end 
ps8[6:]

6    14
7    16
8    18
9    20
dtype: int32

In [177]:
# Reverse order extract - Extract all the element start from index position -1 
ps8[-1:]

9    20
dtype: int32

In [179]:
# start from -4 which is 6 till end 
ps8[-4:]

6    14
7    16
8    18
9    20
dtype: int32

In [180]:
# Basic Math Operation on Series 

ps9 = pd.Series(np.arange(4,41,4))
ps9

0     4
1     8
2    12
3    16
4    20
5    24
6    28
7    32
8    36
9    40
dtype: int32

In [181]:
# Adding 4 in element and every element of the series 
ps9 + 4

0     8
1    12
2    16
3    20
4    24
5    28
6    32
7    36
8    40
9    44
dtype: int32

In [187]:
# Adding the two series objects 

ps10 = ps9
ps11 = pd.Series(np.arange(5,51,4))

In [188]:
ps10

0     4
1     8
2    12
3    16
4    20
5    24
6    28
7    32
8    36
9    40
dtype: int32

In [189]:
ps11

0      5
1      9
2     13
3     17
4     21
5     25
6     29
7     33
8     37
9     41
10    45
11    49
dtype: int32

In [190]:
# Adding the two series 
ps10+ps11

# value shown NaN has no value on one the series index places

0      9.0
1     17.0
2     25.0
3     33.0
4     41.0
5     49.0
6     57.0
7     65.0
8     73.0
9     81.0
10     NaN
11     NaN
dtype: float64

In [191]:
ps10 - ps11

0    -1.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5    -1.0
6    -1.0
7    -1.0
8    -1.0
9    -1.0
10    NaN
11    NaN
dtype: float64

##### Pandas Data Frame

- A data frame comprises of rows and columns
- Dataframe is a 2 dimensional labelled data structure 

In [196]:
# Create a dataframe 

df1 = pd.DataFrame({"subjects":['maths', 'chemistry', 'biology', 'physics'], "marks": [65,91,67,73]})
df1

# below we can see dataframe created start with index on left most

subjects  marks
0      maths     65
1  chemistry     91
2    biology     67
3    physics     73

In [197]:
# Dataframe in - built functions 

# head

df1.head() #this show top 5 record by default of a df

subjects  marks
0      maths     65
1  chemistry     91
2    biology     67
3    physics     73

In [198]:
df1.shape # show the shape of the df - rows, columns

(4, 2)

In [199]:
df1.describe() # gives us basic statistics of the numerical columns of the df

marks
count   4.00000
mean   74.00000
std    11.83216
min    65.00000
25%    66.50000
50%    70.00000
75%    77.50000
max    91.00000

In [201]:
df1.tail() # show the bottom 5 record of the dataframe by default

subjects  marks
0      maths     65
1  chemistry     91
2    biology     67
3    physics     73

In [209]:
# loading iris dataframe 

from sklearn.datasets import load_iris

In [222]:
iris = pd.read_csv('D:\\Users\mahesh.sharma\Documents\Python Scripts\iris_csv.csv')

In [223]:
type(iris)

pandas.core.frame.DataFrame

In [224]:
iris.head() # top 5 records

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [226]:
iris.tail() # last 5 records

sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [225]:
iris.shape # 150 rows with 5 columns

(150, 5)

In [227]:
iris.describe()

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

##### Extract individual columns from the data frame  -- > .loc and iloc

- iloc --> helps to extract rows and columns with respect to its index position
- loc --> 

In [228]:
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [230]:
# iloc syntax --> iloc[start from for rows: end for rows, start from for columns: end for columns]

iris.iloc[0:3,0:4] # this will extract first 3 rows and first 4 columns

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2

In [232]:
iris.iloc[1:3,2:4]

petallength  petalwidth
1          1.4         0.2
2          1.3         0.2

In [234]:
iris.iloc[:100,0:] # this will give us first 100  rows records with all columns as no end position mentioned for column

sepallength  sepalwidth  petallength  petalwidth            class
0           5.1         3.5          1.4         0.2      Iris-setosa
1           4.9         3.0          1.4         0.2      Iris-setosa
2           4.7         3.2          1.3         0.2      Iris-setosa
3           4.6         3.1          1.5         0.2      Iris-setosa
4           5.0         3.6          1.4         0.2      Iris-setosa
..          ...         ...          ...         ...              ...
95          5.7         3.0          4.2         1.2  Iris-versicolor
96          5.7         2.9          4.2         1.3  Iris-versicolor
97          6.2         2.9          4.3         1.3  Iris-versicolor
98          5.1         2.5          3.0         1.1  Iris-versicolor
99          5.7         2.8          4.1         1.3  Iris-versicolor

[100 rows x 5 columns]

In [236]:
# Using loc methos extract columns with their name
iris.loc[0:10, ('class','sepallength','petallength')] 

class  sepallength  petallength
0   Iris-setosa          5.1          1.4
1   Iris-setosa          4.9          1.4
2   Iris-setosa          4.7          1.3
3   Iris-setosa          4.6          1.5
4   Iris-setosa          5.0          1.4
5   Iris-setosa          5.4          1.7
6   Iris-setosa          4.6          1.4
7   Iris-setosa          5.0          1.5
8   Iris-setosa          4.4          1.4
9   Iris-setosa          4.9          1.5
10  Iris-setosa          5.4          1.5

In [237]:
# dropping columns from the data frame

iris.drop('petalwidth', axis=1) # here axis 1 indicates column

sepallength  sepalwidth  petallength           class
0            5.1         3.5          1.4     Iris-setosa
1            4.9         3.0          1.4     Iris-setosa
2            4.7         3.2          1.3     Iris-setosa
3            4.6         3.1          1.5     Iris-setosa
4            5.0         3.6          1.4     Iris-setosa
..           ...         ...          ...             ...
145          6.7         3.0          5.2  Iris-virginica
146          6.3         2.5          5.0  Iris-virginica
147          6.5         3.0          5.2  Iris-virginica
148          6.2         3.4          5.4  Iris-virginica
149          5.9         3.0          5.1  Iris-virginica

[150 rows x 4 columns]

In [244]:
iris.drop([1,2,3,4],axis=0) # this drops the given index position rows 

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
5            5.4         3.9          1.7         0.4     Iris-setosa
6            4.6         3.4          1.4         0.3     Iris-setosa
7            5.0         3.4          1.5         0.2     Iris-setosa
8            4.4         2.9          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[146 rows x 5 columns]

In [245]:
# Data Frame Functions 
iris.mean()

sepallength    5.843333
sepalwidth     3.054000
petallength    3.758667
petalwidth     1.198667
dtype: float64

In [246]:
iris.median()

sepallength    5.80
sepalwidth     3.00
petallength    4.35
petalwidth     1.30
dtype: float64

In [247]:
iris.max()

sepallength               7.9
sepalwidth                4.4
petallength               6.9
petalwidth                2.5
class          Iris-virginica
dtype: object

In [248]:
iris.min()

sepallength            4.3
sepalwidth             2.0
petallength            1.0
petalwidth             0.1
class          Iris-setosa
dtype: object

In [249]:
iris.std()

sepallength    0.828066
sepalwidth     0.433594
petallength    1.764420
petalwidth     0.763161
dtype: float64

In [252]:
# Extract specific columns from df 

iris[['sepallength']] # single column

sepallength
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
..           ...
145          6.7
146          6.3
147          6.5
148          6.2
149          5.9

[150 rows x 1 columns]

In [251]:
iris[['petalwidth','petalwidth']]

petalwidth  petalwidth
0           0.2         0.2
1           0.2         0.2
2           0.2         0.2
3           0.2         0.2
4           0.2         0.2
..          ...         ...
145         2.3         2.3
146         1.9         1.9
147         2.0         2.0
148         2.3         2.3
149         1.8         1.8

[150 rows x 2 columns]

In [ ]:
# apply method - when we want to apply same function on the different columns then we use the apply method

In [253]:
def multiple_by2(x):
    return x*2

In [254]:
multiple_by2(10) # check if the function working fine

20

In [256]:
iris[['petalwidth','petalwidth']].head()

petalwidth  petalwidth
0         0.2         0.2
1         0.2         0.2
2         0.2         0.2
3         0.2         0.2
4         0.2         0.2

In [257]:
iris[['petalwidth','petalwidth']].apply(multiple_by2).head() # here values are multiple by 2 

petalwidth  petalwidth
0         0.4         0.4
1         0.4         0.4
2         0.4         0.4
3         0.4         0.4
4         0.4         0.4

In [259]:
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [260]:
def max_val(s):
    return max(s)

In [261]:
def min_val(s):
    return min(s)

In [262]:
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [268]:
iris.iloc[0:5,0:4].apply(min_val) # apply min function on top 5 rows of iris data sets column

sepallength    4.6
sepalwidth     3.0
petallength    1.3
petalwidth     0.2
dtype: float64

In [273]:
iris[['sepallength']].apply(max_val)

sepallength    7.9
dtype: float64

In [272]:
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [285]:
# value_counts - to check the no of records in the data frame 
print(iris.columns) # check column names 
print(type(iris))

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')
<class 'pandas.core.frame.DataFrame'>


In [287]:
iris['class'].value_counts() # Gives you count of every element of column class

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: class, dtype: int64

In [288]:
iris.sort_values(by = 'sepallength') # sort the values of a dataframe by sepallength column desc order

sepallength  sepalwidth  petallength  petalwidth           class
13           4.3         3.0          1.1         0.1     Iris-setosa
42           4.4         3.2          1.3         0.2     Iris-setosa
38           4.4         3.0          1.3         0.2     Iris-setosa
8            4.4         2.9          1.4         0.2     Iris-setosa
41           4.5         2.3          1.3         0.3     Iris-setosa
..           ...         ...          ...         ...             ...
122          7.7         2.8          6.7         2.0  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica

[150 rows x 5 columns]

In [290]:
iris.sort_values(by = ('sepalwidth'))

sepallength  sepalwidth  petallength  petalwidth            class
60           5.0         2.0          3.5         1.0  Iris-versicolor
62           6.0         2.2          4.0         1.0  Iris-versicolor
119          6.0         2.2          5.0         1.5   Iris-virginica
68           6.2         2.2          4.5         1.5  Iris-versicolor
41           4.5         2.3          1.3         0.3      Iris-setosa
..           ...         ...          ...         ...              ...
16           5.4         3.9          1.3         0.4      Iris-setosa
14           5.8         4.0          1.2         0.2      Iris-setosa
32           5.2         4.1          1.5         0.1      Iris-setosa
33           5.5         4.2          1.4         0.2      Iris-setosa
15           5.7         4.4          1.5         0.4      Iris-setosa

[150 rows x 5 columns]